### ISSUE TITLE
when sent ics file as attachment in mail

### ISSUE THREAD

**Issue by sureshp83** [sssurii/laravel-ics#1]
i want this kind of functionality
when sent ics file as an attachment in the mail make it will open directly in calendar instead of download

**Comment by sssurii** [comment]
@sureshp83 Thanks for raising the point. 
Although it is supposed to show the invitation details in the email and should show the calendar option too.
It will be a great help if you can send provide me with more detail, like the email domain (i.e. gmail or hotmail etc), the browser you are using.
Also example event details you are setting to send the invitation.
Thanks

**Comment by sssurii** [comment]
As no further updates were provided, so marking it as closed
