### ISSUE TITLE
Constants file is missing.

### ISSUE THREAD

**Issue by anoop-fxbytes** [sssurii/laravel-ics#4]
Hello Dear please add the constants file also.

**Comment by sssurii** [comment]
@anoop-fxbytes : Thanks for spotting it. I will include it soon and update here.

**Comment by sssurii** [comment]
@anoop-fxbytes : I have updated the package to include the config file as `ics.php` instead of the constants file.
You can review the PR: https://github.com/sssurii/laravel-ics/pull/5
 I am marking this issue as closed now.
